/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: themaker845 (https://sketchfab.com/themaker845)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-787-dreamliner-524f485c748146b7968e0dd8eb84e786
Title: Boeing-787- Dreamliner
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.89}>
          <group name="Root">
            <group name="Boeing_787_Dreamliner001" position={[-0.21, -1.63, 0.06]} scale={0.4}>
              <group name="Zylinder001" position={[1.61, -0.16, -0.51]} rotation={[0.27, -1.51, -1.29]} scale={-1}>
                <mesh name="Zylinder001_0" geometry={nodes.Zylinder001_0.geometry} material={materials['Material.055']} morphTargetDictionary={nodes.Zylinder001_0.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder001_0.morphTargetInfluences} />
                <mesh name="Zylinder001_1" geometry={nodes.Zylinder001_1.geometry} material={materials['BMD_Rubber_0004.002']} morphTargetDictionary={nodes.Zylinder001_1.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder001_1.morphTargetInfluences} />
                <mesh name="Zylinder001_2" geometry={nodes.Zylinder001_2.geometry} material={materials['Material.056']} morphTargetDictionary={nodes.Zylinder001_2.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder001_2.morphTargetInfluences} />
              </group>
              <group name="Zylinder000" position={[-3.46, 3.48, -0.87]} rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
                <mesh name="Zylinder000_0" geometry={nodes.Zylinder000_0.geometry} material={materials['Material.469']} />
                <mesh name="Zylinder000_1" geometry={nodes.Zylinder000_1.geometry} material={materials['Material.470']} />
                <mesh name="Zylinder000_2" geometry={nodes.Zylinder000_2.geometry} material={materials['Material.471']} />
                <mesh name="Zylinder000_3" geometry={nodes.Zylinder000_3.geometry} material={materials['Material.472']} />
              </group>
              <group name="Zylinder004" position={[3.45, 3.48, -0.85]} rotation={[Math.PI / 2, 0, 0]} scale={0.11}>
                <mesh name="Zylinder004_0" geometry={nodes.Zylinder004_0.geometry} material={materials['Material.469']} />
                <mesh name="Zylinder004_1" geometry={nodes.Zylinder004_1.geometry} material={materials['Material.470']} />
                <mesh name="Zylinder004_2" geometry={nodes.Zylinder004_2.geometry} material={materials['Material.471']} />
                <mesh name="Zylinder004_3" geometry={nodes.Zylinder004_3.geometry} material={materials['Material.472']} />
              </group>
              <group name="Zylinder005" position={[-1.6, -0.26, -0.42]} rotation={[1.59, 0.03, 1.54]}>
                <mesh name="Zylinder005_0" geometry={nodes.Zylinder005_0.geometry} material={materials['Material.055']} morphTargetDictionary={nodes.Zylinder005_0.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder005_0.morphTargetInfluences} />
                <mesh name="Zylinder005_1" geometry={nodes.Zylinder005_1.geometry} material={materials['BMD_Rubber_0004.002']} morphTargetDictionary={nodes.Zylinder005_1.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder005_1.morphTargetInfluences} />
                <mesh name="Zylinder005_2" geometry={nodes.Zylinder005_2.geometry} material={materials['Material.056']} morphTargetDictionary={nodes.Zylinder005_2.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder005_2.morphTargetInfluences} />
              </group>
              <group name="Zylinder006" position={[0.01, 4.81, -0.08]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh name="Zylinder006_0" geometry={nodes.Zylinder006_0.geometry} material={materials['Material.057']} morphTargetDictionary={nodes.Zylinder006_0.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder006_0.morphTargetInfluences} />
                <mesh name="Zylinder006_1" geometry={nodes.Zylinder006_1.geometry} material={materials['Material.058']} morphTargetDictionary={nodes.Zylinder006_1.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder006_1.morphTargetInfluences} />
                <mesh name="Zylinder006_2" geometry={nodes.Zylinder006_2.geometry} material={materials['Material.059']} morphTargetDictionary={nodes.Zylinder006_2.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder006_2.morphTargetInfluences} />
              </group>
              <group name="Zylinder007" position={[0, 7.89, -0.66]} rotation={[1.48, 0, Math.PI / 2]}>
                <mesh name="Zylinder007_0" geometry={nodes.Zylinder007_0.geometry} material={materials['Material.055']} morphTargetDictionary={nodes.Zylinder007_0.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder007_0.morphTargetInfluences} />
                <mesh name="Zylinder007_1" geometry={nodes.Zylinder007_1.geometry} material={materials['BMD_Rubber_0004.002']} morphTargetDictionary={nodes.Zylinder007_1.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder007_1.morphTargetInfluences} />
                <mesh name="Zylinder007_2" geometry={nodes.Zylinder007_2.geometry} material={materials['Material.056']} morphTargetDictionary={nodes.Zylinder007_2.morphTargetDictionary} morphTargetInfluences={nodes.Zylinder007_2.morphTargetInfluences} />
              </group>
              <mesh name="Boeing_787_Dreamliner001_0" geometry={nodes.Boeing_787_Dreamliner001_0.geometry} material={materials.Interior_gray} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_0.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_0.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_1" geometry={nodes.Boeing_787_Dreamliner001_1.geometry} material={materials.Light_A} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_1.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_1.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_2" geometry={nodes.Boeing_787_Dreamliner001_2.geometry} material={materials.Inetrior_Blue} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_2.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_2.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_3" geometry={nodes.Boeing_787_Dreamliner001_3.geometry} material={materials.Outside_Right} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_3.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_3.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_4" geometry={nodes.Boeing_787_Dreamliner001_4.geometry} material={materials.Glass} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_4.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_4.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_5" geometry={nodes.Boeing_787_Dreamliner001_5.geometry} material={materials.Interior_wight} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_5.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_5.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_6" geometry={nodes.Boeing_787_Dreamliner001_6.geometry} material={materials.Cockpit_black} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_6.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_6.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_7" geometry={nodes.Boeing_787_Dreamliner001_7.geometry} material={materials['Cockpit_gray.001']} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_7.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_7.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_8" geometry={nodes.Boeing_787_Dreamliner001_8.geometry} material={materials.Cockpit_gray} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_8.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_8.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_9" geometry={nodes.Boeing_787_Dreamliner001_9.geometry} material={materials.COkpit_black} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_9.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_9.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_10" geometry={nodes.Boeing_787_Dreamliner001_10.geometry} material={materials.Cockpit_blue} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_10.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_10.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_11" geometry={nodes.Boeing_787_Dreamliner001_11.geometry} material={materials.Cockpit_chair_gray} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_11.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_11.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_12" geometry={nodes.Boeing_787_Dreamliner001_12.geometry} material={materials.Storage} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_12.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_12.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_13" geometry={nodes.Boeing_787_Dreamliner001_13.geometry} material={materials.Light_red} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_13.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_13.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_14" geometry={nodes.Boeing_787_Dreamliner001_14.geometry} material={materials.light_green} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_14.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_14.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_15" geometry={nodes.Boeing_787_Dreamliner001_15.geometry} material={materials.Floor} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_15.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_15.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_16" geometry={nodes.Boeing_787_Dreamliner001_16.geometry} material={materials.Chair_blue} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_16.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_16.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_17" geometry={nodes.Boeing_787_Dreamliner001_17.geometry} material={materials.Cjair_gray} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_17.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_17.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_18" geometry={nodes.Boeing_787_Dreamliner001_18.geometry} material={materials.Chair_black} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_18.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_18.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_19" geometry={nodes.Boeing_787_Dreamliner001_19.geometry} material={materials.white} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_19.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_19.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_20" geometry={nodes.Boeing_787_Dreamliner001_20.geometry} material={materials.Outsinde_left} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_20.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_20.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_21" geometry={nodes.Boeing_787_Dreamliner001_21.geometry} material={materials.outside_glossy} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_21.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_21.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_22" geometry={nodes.Boeing_787_Dreamliner001_22.geometry} material={materials['Cockpit_texture.001']} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_22.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_22.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_23" geometry={nodes.Boeing_787_Dreamliner001_23.geometry} material={materials['Cockpit_texture.002']} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_23.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_23.morphTargetInfluences} />
              <mesh name="Boeing_787_Dreamliner001_24" geometry={nodes.Boeing_787_Dreamliner001_24.geometry} material={materials.Cockpit_texture} morphTargetDictionary={nodes.Boeing_787_Dreamliner001_24.morphTargetDictionary} morphTargetInfluences={nodes.Boeing_787_Dreamliner001_24.morphTargetInfluences} />
            </group>
            <group name="Plane" position={[-0.52, 0.06, -0.74]} rotation={[0, 0, -Math.PI]} scale={-5.49}>
              <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials.BakedCycles} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
